spring:
  application:
    name: exammock

    # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: "password"
      # Hibernate Properties
  jpa:
    show-sql: false
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: "TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg=\r\n"